#!/bin/bash

function audit_subdomain {
    domain="$1"
    subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        # Display information for all subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        # Display information for the specified subdomain
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

# Usage: ./0-world_wide_web domain [subdomain]
audit_subdomain "$@"

