#!/usr/bin/env bash
# Install and configure Nginx on an Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo ufw allow 'Nginx HTTP'
