#!/usr/bin/env bash
# Create a backup of the default Nginx configuration file
sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo ufw allow 'Nginx HTTP'
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx reload
