#!/usr/bin/env bash
# nginx configuration for setting up a new ubuntu mechine
sudo apt-get update
sudo apt-get install -y nginx

# start nginx server
sudo service nginx start

# write hello world in the /var/www/html/index.nginx-debian.html to make helloworld in the home page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# giving or making nginx listen to HTTP port which is 80
sudo ufw allow 'Nginx HTTP'
# copy the default file inside sites-available to default.bak to recover it if something goes wrong
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# inserts a redirection information. if the path given is /redirect_me it redirects it to google
redirect="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
# replaces the server_name _; with the rewrite for redirection
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default
# creates a 404 html file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
epage="server_name _;\n\terror_page 404 \/404.html;"
sudo sed -i "s/server_name _;/$epage/" /etc/nginx/sites-enabled/default
# restarts nginx
sudo service nginx restart
