#!/usr/bin/env bash
# installing and configuring loadbalancer using HAproxy
# install HAproxy for ubuntu 20.04 LTS
# sudo apt-get install --no-install-recommends software-properties-common -y
# sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y -s
# sudo apt-get install haproxy=2.8.\* -y
# start haproxy
sudo service haproxy start
# adding HAproxy configuration both servers for backend and defining frontend configurations
toadd="\nfrontend http-in\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver server1 54.87.151.225:80 check\n\tserver server2 3.90.70.140:80 check"
echo -e $toadd | sudo tee /etc/haproxy/haproxy.cfg
# restart haproxy
sudo service haproxy restart
