#!/usr/bin/env bash
# installing and configuring loadbalancer using HAproxy
# install HAproxy for ubuntu 20.04 LTS
sudo apt install -y --no-install-recommends software-properties-common
sudo apt-get -y update
sudo apt-get install -y haproxy
# start haproxy
sudo service haproxy start
# adding HAproxy configuration both servers for backend and defining frontend configurations
toadd="\nfrontend http-in\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 203835-web-01 54.87.151.225:80 check\n\tserver 203835-web-02 3.90.70.140:80 check"
echo -e $toadd | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# restart haproxy
sudo service haproxy restart
