#!/usr/bin/env bash
# a script that pings an IP address passed as an argument.
if [ $# == 0 ]; then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
        for ((i=0; i<5; i++))
        do
                ping -c 5 "$1"
        done
fi
