#!/usr/bin/env bash
# makes localhost resolve to 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1[[:space:]]*localhost/127.0.0.2\tlocalhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
